# Generated by Django 4.0 on 2022-01-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=60)),
                ('DESCRIPTION', models.TextField(max_length=50)),
                ('COSTPERITEM', models.DecimalField(decimal_places=3, max_digits=7)),
                ('STOCKQUANTITY', models.IntegerField()),
                ('VOLUME', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
    ]
